#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HKQTravel.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HKQTravel1")]
	public partial class HKQTravelDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertadmin_account(admin_account instance);
    partial void Updateadmin_account(admin_account instance);
    partial void Deleteadmin_account(admin_account instance);
    partial void Insertuser_account(user_account instance);
    partial void Updateuser_account(user_account instance);
    partial void Deleteuser_account(user_account instance);
    partial void Insertbill_flight(bill_flight instance);
    partial void Updatebill_flight(bill_flight instance);
    partial void Deletebill_flight(bill_flight instance);
    partial void Insertbill_hotel(bill_hotel instance);
    partial void Updatebill_hotel(bill_hotel instance);
    partial void Deletebill_hotel(bill_hotel instance);
    partial void Insertbill_tour(bill_tour instance);
    partial void Updatebill_tour(bill_tour instance);
    partial void Deletebill_tour(bill_tour instance);
    partial void Insertclass(@class instance);
    partial void Updateclass(@class instance);
    partial void Deleteclass(@class instance);
    partial void Insertdeparture_point(departure_point instance);
    partial void Updatedeparture_point(departure_point instance);
    partial void Deletedeparture_point(departure_point instance);
    partial void Insertdestination_point(destination_point instance);
    partial void Updatedestination_point(destination_point instance);
    partial void Deletedestination_point(destination_point instance);
    partial void Insertdiscount(discount instance);
    partial void Updatediscount(discount instance);
    partial void Deletediscount(discount instance);
    partial void Insertflight(flight instance);
    partial void Updateflight(flight instance);
    partial void Deleteflight(flight instance);
    partial void Insertflight_brand(flight_brand instance);
    partial void Updateflight_brand(flight_brand instance);
    partial void Deleteflight_brand(flight_brand instance);
    partial void Inserthotel(hotel instance);
    partial void Updatehotel(hotel instance);
    partial void Deletehotel(hotel instance);
    partial void Inserttour(tour instance);
    partial void Updatetour(tour instance);
    partial void Deletetour(tour instance);
    partial void Inserttour_type(tour_type instance);
    partial void Updatetour_type(tour_type instance);
    partial void Deletetour_type(tour_type instance);
        #endregion

        public HKQTravelDataContext() :
            base(global::System.Configuration.ConfigurationManager.ConnectionStrings["HKQTravel1ConnectionString"].ConnectionString, mappingSource)
        {
            OnCreated();
        }

        public HKQTravelDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HKQTravelDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HKQTravelDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HKQTravelDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<admin_account> admin_accounts
		{
			get
			{
				return this.GetTable<admin_account>();
			}
		}
		
		public System.Data.Linq.Table<user_account> user_accounts
		{
			get
			{
				return this.GetTable<user_account>();
			}
		}
		
		public System.Data.Linq.Table<bill_flight> bill_flights
		{
			get
			{
				return this.GetTable<bill_flight>();
			}
		}
		
		public System.Data.Linq.Table<bill_hotel> bill_hotels
		{
			get
			{
				return this.GetTable<bill_hotel>();
			}
		}
		
		public System.Data.Linq.Table<bill_tour> bill_tours
		{
			get
			{
				return this.GetTable<bill_tour>();
			}
		}
		
		public System.Data.Linq.Table<@class> classes
		{
			get
			{
				return this.GetTable<@class>();
			}
		}
		
		public System.Data.Linq.Table<departure_point> departure_points
		{
			get
			{
				return this.GetTable<departure_point>();
			}
		}
		
		public System.Data.Linq.Table<destination_point> destination_points
		{
			get
			{
				return this.GetTable<destination_point>();
			}
		}
		
		public System.Data.Linq.Table<discount> discounts
		{
			get
			{
				return this.GetTable<discount>();
			}
		}
		
		public System.Data.Linq.Table<flight> flights
		{
			get
			{
				return this.GetTable<flight>();
			}
		}
		
		public System.Data.Linq.Table<flight_brand> flight_brands
		{
			get
			{
				return this.GetTable<flight_brand>();
			}
		}
		
		public System.Data.Linq.Table<hotel> hotels
		{
			get
			{
				return this.GetTable<hotel>();
			}
		}
		
		public System.Data.Linq.Table<tour> tours
		{
			get
			{
				return this.GetTable<tour>();
			}
		}
		
		public System.Data.Linq.Table<tour_type> tour_types
		{
			get
			{
				return this.GetTable<tour_type>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_account")]
	public partial class admin_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _admin_id;
		
		private string _admin_user;
		
		private string _admin_password;
		
		private string _admin_fulllname;
		
		private string _email;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<System.DateTime> _update_date;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onadmin_idChanging(long value);
    partial void Onadmin_idChanged();
    partial void Onadmin_userChanging(string value);
    partial void Onadmin_userChanged();
    partial void Onadmin_passwordChanging(string value);
    partial void Onadmin_passwordChanged();
    partial void Onadmin_fulllnameChanging(string value);
    partial void Onadmin_fulllnameChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dateChanged();
    #endregion
		
		public admin_account()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long admin_id
		{
			get
			{
				return this._admin_id;
			}
			set
			{
				if ((this._admin_id != value))
				{
					this.Onadmin_idChanging(value);
					this.SendPropertyChanging();
					this._admin_id = value;
					this.SendPropertyChanged("admin_id");
					this.Onadmin_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_user", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string admin_user
		{
			get
			{
				return this._admin_user;
			}
			set
			{
				if ((this._admin_user != value))
				{
					this.Onadmin_userChanging(value);
					this.SendPropertyChanging();
					this._admin_user = value;
					this.SendPropertyChanged("admin_user");
					this.Onadmin_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_password", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string admin_password
		{
			get
			{
				return this._admin_password;
			}
			set
			{
				if ((this._admin_password != value))
				{
					this.Onadmin_passwordChanging(value);
					this.SendPropertyChanging();
					this._admin_password = value;
					this.SendPropertyChanged("admin_password");
					this.Onadmin_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_admin_fulllname", DbType="NVarChar(50)")]
		public string admin_fulllname
		{
			get
			{
				return this._admin_fulllname;
			}
			set
			{
				if ((this._admin_fulllname != value))
				{
					this.Onadmin_fulllnameChanging(value);
					this.SendPropertyChanging();
					this._admin_fulllname = value;
					this.SendPropertyChanged("admin_fulllname");
					this.Onadmin_fulllnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(150)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this.Onupdate_dateChanging(value);
					this.SendPropertyChanging();
					this._update_date = value;
					this.SendPropertyChanged("update_date");
					this.Onupdate_dateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.user_account")]
	public partial class user_account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _user_id;
		
		private string _user_name;
		
		private string _user_password;
		
		private string _user_fullname;
		
		private string _phone_number;
		
		private string _email;
		
		private System.Nullable<System.DateTime> _birthday;
		
		private string _address;
		
		private string _sex;
		
		private string _user_image;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<System.DateTime> _update_date;
		
		private System.Nullable<int> _status;
		
		private EntitySet<bill_flight> _bill_flights;
		
		private EntitySet<bill_hotel> _bill_hotels;
		
		private EntitySet<bill_tour> _bill_tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(long value);
    partial void Onuser_idChanged();
    partial void Onuser_nameChanging(string value);
    partial void Onuser_nameChanged();
    partial void Onuser_passwordChanging(string value);
    partial void Onuser_passwordChanged();
    partial void Onuser_fullnameChanging(string value);
    partial void Onuser_fullnameChanged();
    partial void Onphone_numberChanging(string value);
    partial void Onphone_numberChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnbirthdayChanging(System.Nullable<System.DateTime> value);
    partial void OnbirthdayChanged();
    partial void OnaddressChanging(string value);
    partial void OnaddressChanged();
    partial void OnsexChanging(string value);
    partial void OnsexChanged();
    partial void Onuser_imageChanging(string value);
    partial void Onuser_imageChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dateChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public user_account()
		{
			this._bill_flights = new EntitySet<bill_flight>(new Action<bill_flight>(this.attach_bill_flights), new Action<bill_flight>(this.detach_bill_flights));
			this._bill_hotels = new EntitySet<bill_hotel>(new Action<bill_hotel>(this.attach_bill_hotels), new Action<bill_hotel>(this.detach_bill_hotels));
			this._bill_tours = new EntitySet<bill_tour>(new Action<bill_tour>(this.attach_bill_tours), new Action<bill_tour>(this.detach_bill_tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_name", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_name
		{
			get
			{
				return this._user_name;
			}
			set
			{
				if ((this._user_name != value))
				{
					this.Onuser_nameChanging(value);
					this.SendPropertyChanging();
					this._user_name = value;
					this.SendPropertyChanged("user_name");
					this.Onuser_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_password", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string user_password
		{
			get
			{
				return this._user_password;
			}
			set
			{
				if ((this._user_password != value))
				{
					this.Onuser_passwordChanging(value);
					this.SendPropertyChanging();
					this._user_password = value;
					this.SendPropertyChanged("user_password");
					this.Onuser_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_fullname", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string user_fullname
		{
			get
			{
				return this._user_fullname;
			}
			set
			{
				if ((this._user_fullname != value))
				{
					this.Onuser_fullnameChanging(value);
					this.SendPropertyChanging();
					this._user_fullname = value;
					this.SendPropertyChanged("user_fullname");
					this.Onuser_fullnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_number", DbType="VarChar(20)")]
		public string phone_number
		{
			get
			{
				return this._phone_number;
			}
			set
			{
				if ((this._phone_number != value))
				{
					this.Onphone_numberChanging(value);
					this.SendPropertyChanging();
					this._phone_number = value;
					this.SendPropertyChanged("phone_number");
					this.Onphone_numberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_birthday", DbType="DateTime")]
		public System.Nullable<System.DateTime> birthday
		{
			get
			{
				return this._birthday;
			}
			set
			{
				if ((this._birthday != value))
				{
					this.OnbirthdayChanging(value);
					this.SendPropertyChanging();
					this._birthday = value;
					this.SendPropertyChanged("birthday");
					this.OnbirthdayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address", DbType="NVarChar(150)")]
		public string address
		{
			get
			{
				return this._address;
			}
			set
			{
				if ((this._address != value))
				{
					this.OnaddressChanging(value);
					this.SendPropertyChanging();
					this._address = value;
					this.SendPropertyChanged("address");
					this.OnaddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sex", DbType="VarChar(5)")]
		public string sex
		{
			get
			{
				return this._sex;
			}
			set
			{
				if ((this._sex != value))
				{
					this.OnsexChanging(value);
					this.SendPropertyChanging();
					this._sex = value;
					this.SendPropertyChanged("sex");
					this.OnsexChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_image", DbType="VarChar(MAX)")]
		public string user_image
		{
			get
			{
				return this._user_image;
			}
			set
			{
				if ((this._user_image != value))
				{
					this.Onuser_imageChanging(value);
					this.SendPropertyChanging();
					this._user_image = value;
					this.SendPropertyChanged("user_image");
					this.Onuser_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this.Onupdate_dateChanging(value);
					this.SendPropertyChanging();
					this._update_date = value;
					this.SendPropertyChanged("update_date");
					this.Onupdate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_bill_flight", Storage="_bill_flights", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<bill_flight> bill_flights
		{
			get
			{
				return this._bill_flights;
			}
			set
			{
				this._bill_flights.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_bill_hotel", Storage="_bill_hotels", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<bill_hotel> bill_hotels
		{
			get
			{
				return this._bill_hotels;
			}
			set
			{
				this._bill_hotels.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_bill_tour", Storage="_bill_tours", ThisKey="user_id", OtherKey="user_id")]
		public EntitySet<bill_tour> bill_tours
		{
			get
			{
				return this._bill_tours;
			}
			set
			{
				this._bill_tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bill_flights(bill_flight entity)
		{
			this.SendPropertyChanging();
			entity.user_account = this;
		}
		
		private void detach_bill_flights(bill_flight entity)
		{
			this.SendPropertyChanging();
			entity.user_account = null;
		}
		
		private void attach_bill_hotels(bill_hotel entity)
		{
			this.SendPropertyChanging();
			entity.user_account = this;
		}
		
		private void detach_bill_hotels(bill_hotel entity)
		{
			this.SendPropertyChanging();
			entity.user_account = null;
		}
		
		private void attach_bill_tours(bill_tour entity)
		{
			this.SendPropertyChanging();
			entity.user_account = this;
		}
		
		private void detach_bill_tours(bill_tour entity)
		{
			this.SendPropertyChanging();
			entity.user_account = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bill_flight")]
	public partial class bill_flight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _bill_flight_id;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<long> _user_id;
		
		private System.Nullable<long> _flight_id;
		
		private EntityRef<user_account> _user_account;
		
		private EntityRef<flight> _flight;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbill_flight_idChanging(long value);
    partial void Onbill_flight_idChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void Onuser_idChanging(System.Nullable<long> value);
    partial void Onuser_idChanged();
    partial void Onflight_idChanging(System.Nullable<long> value);
    partial void Onflight_idChanged();
    #endregion
		
		public bill_flight()
		{
			this._user_account = default(EntityRef<user_account>);
			this._flight = default(EntityRef<flight>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bill_flight_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long bill_flight_id
		{
			get
			{
				return this._bill_flight_id;
			}
			set
			{
				if ((this._bill_flight_id != value))
				{
					this.Onbill_flight_idChanging(value);
					this.SendPropertyChanging();
					this._bill_flight_id = value;
					this.SendPropertyChanged("bill_flight_id");
					this.Onbill_flight_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt")]
		public System.Nullable<long> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._user_account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_id", DbType="BigInt")]
		public System.Nullable<long> flight_id
		{
			get
			{
				return this._flight_id;
			}
			set
			{
				if ((this._flight_id != value))
				{
					if (this._flight.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onflight_idChanging(value);
					this.SendPropertyChanging();
					this._flight_id = value;
					this.SendPropertyChanged("flight_id");
					this.Onflight_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_bill_flight", Storage="_user_account", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public user_account user_account
		{
			get
			{
				return this._user_account.Entity;
			}
			set
			{
				user_account previousValue = this._user_account.Entity;
				if (((previousValue != value) 
							|| (this._user_account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user_account.Entity = null;
						previousValue.bill_flights.Remove(this);
					}
					this._user_account.Entity = value;
					if ((value != null))
					{
						value.bill_flights.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("user_account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flight_bill_flight", Storage="_flight", ThisKey="flight_id", OtherKey="flight_id", IsForeignKey=true)]
		public flight flight
		{
			get
			{
				return this._flight.Entity;
			}
			set
			{
				flight previousValue = this._flight.Entity;
				if (((previousValue != value) 
							|| (this._flight.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flight.Entity = null;
						previousValue.bill_flights.Remove(this);
					}
					this._flight.Entity = value;
					if ((value != null))
					{
						value.bill_flights.Add(this);
						this._flight_id = value.flight_id;
					}
					else
					{
						this._flight_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("flight");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bill_hotel")]
	public partial class bill_hotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _bill_hotel_id;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<long> _user_id;
		
		private System.Nullable<long> _hotel_id;
		
		private EntityRef<user_account> _user_account;
		
		private EntityRef<hotel> _hotel;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbill_hotel_idChanging(long value);
    partial void Onbill_hotel_idChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void Onuser_idChanging(System.Nullable<long> value);
    partial void Onuser_idChanged();
    partial void Onhotel_idChanging(System.Nullable<long> value);
    partial void Onhotel_idChanged();
    #endregion
		
		public bill_hotel()
		{
			this._user_account = default(EntityRef<user_account>);
			this._hotel = default(EntityRef<hotel>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bill_hotel_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long bill_hotel_id
		{
			get
			{
				return this._bill_hotel_id;
			}
			set
			{
				if ((this._bill_hotel_id != value))
				{
					this.Onbill_hotel_idChanging(value);
					this.SendPropertyChanging();
					this._bill_hotel_id = value;
					this.SendPropertyChanged("bill_hotel_id");
					this.Onbill_hotel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt")]
		public System.Nullable<long> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._user_account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotel_id", DbType="BigInt")]
		public System.Nullable<long> hotel_id
		{
			get
			{
				return this._hotel_id;
			}
			set
			{
				if ((this._hotel_id != value))
				{
					if (this._hotel.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onhotel_idChanging(value);
					this.SendPropertyChanging();
					this._hotel_id = value;
					this.SendPropertyChanged("hotel_id");
					this.Onhotel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_bill_hotel", Storage="_user_account", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public user_account user_account
		{
			get
			{
				return this._user_account.Entity;
			}
			set
			{
				user_account previousValue = this._user_account.Entity;
				if (((previousValue != value) 
							|| (this._user_account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user_account.Entity = null;
						previousValue.bill_hotels.Remove(this);
					}
					this._user_account.Entity = value;
					if ((value != null))
					{
						value.bill_hotels.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("user_account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hotel_bill_hotel", Storage="_hotel", ThisKey="hotel_id", OtherKey="hotel_id", IsForeignKey=true)]
		public hotel hotel
		{
			get
			{
				return this._hotel.Entity;
			}
			set
			{
				hotel previousValue = this._hotel.Entity;
				if (((previousValue != value) 
							|| (this._hotel.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hotel.Entity = null;
						previousValue.bill_hotels.Remove(this);
					}
					this._hotel.Entity = value;
					if ((value != null))
					{
						value.bill_hotels.Add(this);
						this._hotel_id = value.hotel_id;
					}
					else
					{
						this._hotel_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("hotel");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bill_tour")]
	public partial class bill_tour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _bill_tour_id;
		
		private System.Nullable<decimal> _total;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<int> _quantity;
		
		private System.Nullable<long> _user_id;
		
		private System.Nullable<long> _tour_id;
		
		private EntityRef<user_account> _user_account;
		
		private EntityRef<tour> _tour;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbill_tour_idChanging(long value);
    partial void Onbill_tour_idChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void OnquantityChanging(System.Nullable<int> value);
    partial void OnquantityChanged();
    partial void Onuser_idChanging(System.Nullable<long> value);
    partial void Onuser_idChanged();
    partial void Ontour_idChanging(System.Nullable<long> value);
    partial void Ontour_idChanged();
    #endregion
		
		public bill_tour()
		{
			this._user_account = default(EntityRef<user_account>);
			this._tour = default(EntityRef<tour>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bill_tour_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long bill_tour_id
		{
			get
			{
				return this._bill_tour_id;
			}
			set
			{
				if ((this._bill_tour_id != value))
				{
					this.Onbill_tour_idChanging(value);
					this.SendPropertyChanging();
					this._bill_tour_id = value;
					this.SendPropertyChanged("bill_tour_id");
					this.Onbill_tour_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quantity", DbType="Int")]
		public System.Nullable<int> quantity
		{
			get
			{
				return this._quantity;
			}
			set
			{
				if ((this._quantity != value))
				{
					this.OnquantityChanging(value);
					this.SendPropertyChanging();
					this._quantity = value;
					this.SendPropertyChanged("quantity");
					this.OnquantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="BigInt")]
		public System.Nullable<long> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					if (this._user_account.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tour_id", DbType="BigInt")]
		public System.Nullable<long> tour_id
		{
			get
			{
				return this._tour_id;
			}
			set
			{
				if ((this._tour_id != value))
				{
					if (this._tour.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontour_idChanging(value);
					this.SendPropertyChanging();
					this._tour_id = value;
					this.SendPropertyChanged("tour_id");
					this.Ontour_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="user_account_bill_tour", Storage="_user_account", ThisKey="user_id", OtherKey="user_id", IsForeignKey=true)]
		public user_account user_account
		{
			get
			{
				return this._user_account.Entity;
			}
			set
			{
				user_account previousValue = this._user_account.Entity;
				if (((previousValue != value) 
							|| (this._user_account.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._user_account.Entity = null;
						previousValue.bill_tours.Remove(this);
					}
					this._user_account.Entity = value;
					if ((value != null))
					{
						value.bill_tours.Add(this);
						this._user_id = value.user_id;
					}
					else
					{
						this._user_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("user_account");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tour_bill_tour", Storage="_tour", ThisKey="tour_id", OtherKey="tour_id", IsForeignKey=true)]
		public tour tour
		{
			get
			{
				return this._tour.Entity;
			}
			set
			{
				tour previousValue = this._tour.Entity;
				if (((previousValue != value) 
							|| (this._tour.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tour.Entity = null;
						previousValue.bill_tours.Remove(this);
					}
					this._tour.Entity = value;
					if ((value != null))
					{
						value.bill_tours.Add(this);
						this._tour_id = value.tour_id;
					}
					else
					{
						this._tour_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("tour");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.class")]
	public partial class @class : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _class_id;
		
		private string _class_name;
		
		private EntitySet<flight> _flights;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onclass_idChanging(int value);
    partial void Onclass_idChanged();
    partial void Onclass_nameChanging(string value);
    partial void Onclass_nameChanged();
    #endregion
		
		public @class()
		{
			this._flights = new EntitySet<flight>(new Action<flight>(this.attach_flights), new Action<flight>(this.detach_flights));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int class_id
		{
			get
			{
				return this._class_id;
			}
			set
			{
				if ((this._class_id != value))
				{
					this.Onclass_idChanging(value);
					this.SendPropertyChanging();
					this._class_id = value;
					this.SendPropertyChanged("class_id");
					this.Onclass_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_name", DbType="NVarChar(20)")]
		public string class_name
		{
			get
			{
				return this._class_name;
			}
			set
			{
				if ((this._class_name != value))
				{
					this.Onclass_nameChanging(value);
					this.SendPropertyChanging();
					this._class_name = value;
					this.SendPropertyChanged("class_name");
					this.Onclass_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="class_flight", Storage="_flights", ThisKey="class_id", OtherKey="class_id")]
		public EntitySet<flight> flights
		{
			get
			{
				return this._flights;
			}
			set
			{
				this._flights.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flights(flight entity)
		{
			this.SendPropertyChanging();
			entity.@class = this;
		}
		
		private void detach_flights(flight entity)
		{
			this.SendPropertyChanging();
			entity.@class = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.departure_point")]
	public partial class departure_point : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _departure_id;
		
		private string _departure_name;
		
		private System.Nullable<int> _status;
		
		private EntitySet<tour> _tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondeparture_idChanging(long value);
    partial void Ondeparture_idChanged();
    partial void Ondeparture_nameChanging(string value);
    partial void Ondeparture_nameChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public departure_point()
		{
			this._tours = new EntitySet<tour>(new Action<tour>(this.attach_tours), new Action<tour>(this.detach_tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long departure_id
		{
			get
			{
				return this._departure_id;
			}
			set
			{
				if ((this._departure_id != value))
				{
					this.Ondeparture_idChanging(value);
					this.SendPropertyChanging();
					this._departure_id = value;
					this.SendPropertyChanged("departure_id");
					this.Ondeparture_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string departure_name
		{
			get
			{
				return this._departure_name;
			}
			set
			{
				if ((this._departure_name != value))
				{
					this.Ondeparture_nameChanging(value);
					this.SendPropertyChanging();
					this._departure_name = value;
					this.SendPropertyChanged("departure_name");
					this.Ondeparture_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departure_point_tour", Storage="_tours", ThisKey="departure_id", OtherKey="departure_id")]
		public EntitySet<tour> tours
		{
			get
			{
				return this._tours;
			}
			set
			{
				this._tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.departure_point = this;
		}
		
		private void detach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.departure_point = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.destination_point")]
	public partial class destination_point : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _destination_id;
		
		private string _destination_name;
		
		private string _destination_image;
		
		private System.Nullable<int> _status;
		
		private EntitySet<tour> _tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondestination_idChanging(long value);
    partial void Ondestination_idChanged();
    partial void Ondestination_nameChanging(string value);
    partial void Ondestination_nameChanged();
    partial void Ondestination_imageChanging(string value);
    partial void Ondestination_imageChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public destination_point()
		{
			this._tours = new EntitySet<tour>(new Action<tour>(this.attach_tours), new Action<tour>(this.detach_tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long destination_id
		{
			get
			{
				return this._destination_id;
			}
			set
			{
				if ((this._destination_id != value))
				{
					this.Ondestination_idChanging(value);
					this.SendPropertyChanging();
					this._destination_id = value;
					this.SendPropertyChanged("destination_id");
					this.Ondestination_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string destination_name
		{
			get
			{
				return this._destination_name;
			}
			set
			{
				if ((this._destination_name != value))
				{
					this.Ondestination_nameChanging(value);
					this.SendPropertyChanging();
					this._destination_name = value;
					this.SendPropertyChanged("destination_name");
					this.Ondestination_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_image", DbType="VarChar(MAX)")]
		public string destination_image
		{
			get
			{
				return this._destination_image;
			}
			set
			{
				if ((this._destination_image != value))
				{
					this.Ondestination_imageChanging(value);
					this.SendPropertyChanging();
					this._destination_image = value;
					this.SendPropertyChanged("destination_image");
					this.Ondestination_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="destination_point_tour", Storage="_tours", ThisKey="destination_id", OtherKey="destination_id")]
		public EntitySet<tour> tours
		{
			get
			{
				return this._tours;
			}
			set
			{
				this._tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.destination_point = this;
		}
		
		private void detach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.destination_point = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.discount")]
	public partial class discount : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _discount_id;
		
		private System.Nullable<System.DateTime> _discount_month;
		
		private System.Nullable<double> _percentage;
		
		private string _discount_name;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<System.DateTime> _update_date;
		
		private System.Nullable<int> _status;
		
		private EntitySet<tour> _tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondiscount_idChanging(long value);
    partial void Ondiscount_idChanged();
    partial void Ondiscount_monthChanging(System.Nullable<System.DateTime> value);
    partial void Ondiscount_monthChanged();
    partial void OnpercentageChanging(System.Nullable<double> value);
    partial void OnpercentageChanged();
    partial void Ondiscount_nameChanging(string value);
    partial void Ondiscount_nameChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void Onupdate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_dateChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public discount()
		{
			this._tours = new EntitySet<tour>(new Action<tour>(this.attach_tours), new Action<tour>(this.detach_tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long discount_id
		{
			get
			{
				return this._discount_id;
			}
			set
			{
				if ((this._discount_id != value))
				{
					this.Ondiscount_idChanging(value);
					this.SendPropertyChanging();
					this._discount_id = value;
					this.SendPropertyChanged("discount_id");
					this.Ondiscount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_month", DbType="Date")]
		public System.Nullable<System.DateTime> discount_month
		{
			get
			{
				return this._discount_month;
			}
			set
			{
				if ((this._discount_month != value))
				{
					this.Ondiscount_monthChanging(value);
					this.SendPropertyChanging();
					this._discount_month = value;
					this.SendPropertyChanged("discount_month");
					this.Ondiscount_monthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_percentage", DbType="Float")]
		public System.Nullable<double> percentage
		{
			get
			{
				return this._percentage;
			}
			set
			{
				if ((this._percentage != value))
				{
					this.OnpercentageChanging(value);
					this.SendPropertyChanging();
					this._percentage = value;
					this.SendPropertyChanged("percentage");
					this.OnpercentageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_name", DbType="NVarChar(50)")]
		public string discount_name
		{
			get
			{
				return this._discount_name;
			}
			set
			{
				if ((this._discount_name != value))
				{
					this.Ondiscount_nameChanging(value);
					this.SendPropertyChanging();
					this._discount_name = value;
					this.SendPropertyChanged("discount_name");
					this.Ondiscount_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_date
		{
			get
			{
				return this._update_date;
			}
			set
			{
				if ((this._update_date != value))
				{
					this.Onupdate_dateChanging(value);
					this.SendPropertyChanging();
					this._update_date = value;
					this.SendPropertyChanged("update_date");
					this.Onupdate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="discount_tour", Storage="_tours", ThisKey="discount_id", OtherKey="discount_id")]
		public EntitySet<tour> tours
		{
			get
			{
				return this._tours;
			}
			set
			{
				this._tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.discount = this;
		}
		
		private void detach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.discount = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flight")]
	public partial class flight : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _flight_id;
		
		private string _flight_name;
		
		private string _departure_location;
		
		private string _destination_location;
		
		private System.Nullable<System.DateTime> _start_time;
		
		private System.Nullable<System.DateTime> _return_time;
		
		private System.Nullable<decimal> _price;
		
		private string _number_of_passenger;
		
		private System.Nullable<int> _class_id;
		
		private System.Nullable<int> _flight_brand_id;
		
		private System.Nullable<int> _status;
		
		private EntitySet<bill_flight> _bill_flights;
		
		private EntityRef<@class> _class;
		
		private EntityRef<flight_brand> _flight_brand;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onflight_idChanging(long value);
    partial void Onflight_idChanged();
    partial void Onflight_nameChanging(string value);
    partial void Onflight_nameChanged();
    partial void Ondeparture_locationChanging(string value);
    partial void Ondeparture_locationChanged();
    partial void Ondestination_locationChanging(string value);
    partial void Ondestination_locationChanged();
    partial void Onstart_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onstart_timeChanged();
    partial void Onreturn_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onreturn_timeChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void Onnumber_of_passengerChanging(string value);
    partial void Onnumber_of_passengerChanged();
    partial void Onclass_idChanging(System.Nullable<int> value);
    partial void Onclass_idChanged();
    partial void Onflight_brand_idChanging(System.Nullable<int> value);
    partial void Onflight_brand_idChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public flight()
		{
			this._bill_flights = new EntitySet<bill_flight>(new Action<bill_flight>(this.attach_bill_flights), new Action<bill_flight>(this.detach_bill_flights));
			this._class = default(EntityRef<@class>);
			this._flight_brand = default(EntityRef<flight_brand>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long flight_id
		{
			get
			{
				return this._flight_id;
			}
			set
			{
				if ((this._flight_id != value))
				{
					this.Onflight_idChanging(value);
					this.SendPropertyChanging();
					this._flight_id = value;
					this.SendPropertyChanged("flight_id");
					this.Onflight_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_name", DbType="NVarChar(50)")]
		public string flight_name
		{
			get
			{
				return this._flight_name;
			}
			set
			{
				if ((this._flight_name != value))
				{
					this.Onflight_nameChanging(value);
					this.SendPropertyChanging();
					this._flight_name = value;
					this.SendPropertyChanged("flight_name");
					this.Onflight_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_location", DbType="NVarChar(50)")]
		public string departure_location
		{
			get
			{
				return this._departure_location;
			}
			set
			{
				if ((this._departure_location != value))
				{
					this.Ondeparture_locationChanging(value);
					this.SendPropertyChanging();
					this._departure_location = value;
					this.SendPropertyChanged("departure_location");
					this.Ondeparture_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_location", DbType="NVarChar(50)")]
		public string destination_location
		{
			get
			{
				return this._destination_location;
			}
			set
			{
				if ((this._destination_location != value))
				{
					this.Ondestination_locationChanging(value);
					this.SendPropertyChanging();
					this._destination_location = value;
					this.SendPropertyChanged("destination_location");
					this.Ondestination_locationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_start_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> start_time
		{
			get
			{
				return this._start_time;
			}
			set
			{
				if ((this._start_time != value))
				{
					this.Onstart_timeChanging(value);
					this.SendPropertyChanging();
					this._start_time = value;
					this.SendPropertyChanged("start_time");
					this.Onstart_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_return_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> return_time
		{
			get
			{
				return this._return_time;
			}
			set
			{
				if ((this._return_time != value))
				{
					this.Onreturn_timeChanging(value);
					this.SendPropertyChanging();
					this._return_time = value;
					this.SendPropertyChanged("return_time");
					this.Onreturn_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_of_passenger", DbType="VarChar(5)")]
		public string number_of_passenger
		{
			get
			{
				return this._number_of_passenger;
			}
			set
			{
				if ((this._number_of_passenger != value))
				{
					this.Onnumber_of_passengerChanging(value);
					this.SendPropertyChanging();
					this._number_of_passenger = value;
					this.SendPropertyChanged("number_of_passenger");
					this.Onnumber_of_passengerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_class_id", DbType="Int")]
		public System.Nullable<int> class_id
		{
			get
			{
				return this._class_id;
			}
			set
			{
				if ((this._class_id != value))
				{
					if (this._class.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onclass_idChanging(value);
					this.SendPropertyChanging();
					this._class_id = value;
					this.SendPropertyChanged("class_id");
					this.Onclass_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_brand_id", DbType="Int")]
		public System.Nullable<int> flight_brand_id
		{
			get
			{
				return this._flight_brand_id;
			}
			set
			{
				if ((this._flight_brand_id != value))
				{
					if (this._flight_brand.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onflight_brand_idChanging(value);
					this.SendPropertyChanging();
					this._flight_brand_id = value;
					this.SendPropertyChanged("flight_brand_id");
					this.Onflight_brand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flight_bill_flight", Storage="_bill_flights", ThisKey="flight_id", OtherKey="flight_id")]
		public EntitySet<bill_flight> bill_flights
		{
			get
			{
				return this._bill_flights;
			}
			set
			{
				this._bill_flights.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="class_flight", Storage="_class", ThisKey="class_id", OtherKey="class_id", IsForeignKey=true)]
		public @class @class
		{
			get
			{
				return this._class.Entity;
			}
			set
			{
				@class previousValue = this._class.Entity;
				if (((previousValue != value) 
							|| (this._class.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._class.Entity = null;
						previousValue.flights.Remove(this);
					}
					this._class.Entity = value;
					if ((value != null))
					{
						value.flights.Add(this);
						this._class_id = value.class_id;
					}
					else
					{
						this._class_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("@class");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flight_brand_flight", Storage="_flight_brand", ThisKey="flight_brand_id", OtherKey="flight_brand_id", IsForeignKey=true)]
		public flight_brand flight_brand
		{
			get
			{
				return this._flight_brand.Entity;
			}
			set
			{
				flight_brand previousValue = this._flight_brand.Entity;
				if (((previousValue != value) 
							|| (this._flight_brand.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flight_brand.Entity = null;
						previousValue.flights.Remove(this);
					}
					this._flight_brand.Entity = value;
					if ((value != null))
					{
						value.flights.Add(this);
						this._flight_brand_id = value.flight_brand_id;
					}
					else
					{
						this._flight_brand_id = default(Nullable<int>);
					}
					this.SendPropertyChanged("flight_brand");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bill_flights(bill_flight entity)
		{
			this.SendPropertyChanging();
			entity.flight = this;
		}
		
		private void detach_bill_flights(bill_flight entity)
		{
			this.SendPropertyChanging();
			entity.flight = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flight_brand")]
	public partial class flight_brand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _flight_brand_id;
		
		private string _flight_brand_name;
		
		private string _flight_brand_image;
		
		private EntitySet<flight> _flights;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onflight_brand_idChanging(int value);
    partial void Onflight_brand_idChanged();
    partial void Onflight_brand_nameChanging(string value);
    partial void Onflight_brand_nameChanged();
    partial void Onflight_brand_imageChanging(string value);
    partial void Onflight_brand_imageChanged();
    #endregion
		
		public flight_brand()
		{
			this._flights = new EntitySet<flight>(new Action<flight>(this.attach_flights), new Action<flight>(this.detach_flights));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_brand_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int flight_brand_id
		{
			get
			{
				return this._flight_brand_id;
			}
			set
			{
				if ((this._flight_brand_id != value))
				{
					this.Onflight_brand_idChanging(value);
					this.SendPropertyChanging();
					this._flight_brand_id = value;
					this.SendPropertyChanged("flight_brand_id");
					this.Onflight_brand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_brand_name", DbType="VarChar(50)")]
		public string flight_brand_name
		{
			get
			{
				return this._flight_brand_name;
			}
			set
			{
				if ((this._flight_brand_name != value))
				{
					this.Onflight_brand_nameChanging(value);
					this.SendPropertyChanging();
					this._flight_brand_name = value;
					this.SendPropertyChanged("flight_brand_name");
					this.Onflight_brand_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flight_brand_image", DbType="NVarChar(MAX)")]
		public string flight_brand_image
		{
			get
			{
				return this._flight_brand_image;
			}
			set
			{
				if ((this._flight_brand_image != value))
				{
					this.Onflight_brand_imageChanging(value);
					this.SendPropertyChanging();
					this._flight_brand_image = value;
					this.SendPropertyChanged("flight_brand_image");
					this.Onflight_brand_imageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flight_brand_flight", Storage="_flights", ThisKey="flight_brand_id", OtherKey="flight_brand_id")]
		public EntitySet<flight> flights
		{
			get
			{
				return this._flights;
			}
			set
			{
				this._flights.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flights(flight entity)
		{
			this.SendPropertyChanging();
			entity.flight_brand = this;
		}
		
		private void detach_flights(flight entity)
		{
			this.SendPropertyChanging();
			entity.flight_brand = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hotel")]
	public partial class hotel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _hotel_id;
		
		private string _hotel_name;
		
		private string _location;
		
		private System.Nullable<int> _number_room;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<int> _ranking;
		
		private string _image;
		
		private System.Nullable<int> _status;
		
		private EntitySet<bill_hotel> _bill_hotels;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onhotel_idChanging(long value);
    partial void Onhotel_idChanged();
    partial void Onhotel_nameChanging(string value);
    partial void Onhotel_nameChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void Onnumber_roomChanging(System.Nullable<int> value);
    partial void Onnumber_roomChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void OnrankingChanging(System.Nullable<int> value);
    partial void OnrankingChanged();
    partial void OnimageChanging(string value);
    partial void OnimageChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public hotel()
		{
			this._bill_hotels = new EntitySet<bill_hotel>(new Action<bill_hotel>(this.attach_bill_hotels), new Action<bill_hotel>(this.detach_bill_hotels));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotel_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long hotel_id
		{
			get
			{
				return this._hotel_id;
			}
			set
			{
				if ((this._hotel_id != value))
				{
					this.Onhotel_idChanging(value);
					this.SendPropertyChanging();
					this._hotel_id = value;
					this.SendPropertyChanged("hotel_id");
					this.Onhotel_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hotel_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hotel_name
		{
			get
			{
				return this._hotel_name;
			}
			set
			{
				if ((this._hotel_name != value))
				{
					this.Onhotel_nameChanging(value);
					this.SendPropertyChanging();
					this._hotel_name = value;
					this.SendPropertyChanged("hotel_name");
					this.Onhotel_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(50)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_number_room", DbType="Int")]
		public System.Nullable<int> number_room
		{
			get
			{
				return this._number_room;
			}
			set
			{
				if ((this._number_room != value))
				{
					this.Onnumber_roomChanging(value);
					this.SendPropertyChanging();
					this._number_room = value;
					this.SendPropertyChanged("number_room");
					this.Onnumber_roomChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ranking", DbType="Int")]
		public System.Nullable<int> ranking
		{
			get
			{
				return this._ranking;
			}
			set
			{
				if ((this._ranking != value))
				{
					this.OnrankingChanging(value);
					this.SendPropertyChanging();
					this._ranking = value;
					this.SendPropertyChanged("ranking");
					this.OnrankingChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_image", DbType="VarChar(MAX)")]
		public string image
		{
			get
			{
				return this._image;
			}
			set
			{
				if ((this._image != value))
				{
					this.OnimageChanging(value);
					this.SendPropertyChanging();
					this._image = value;
					this.SendPropertyChanged("image");
					this.OnimageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hotel_bill_hotel", Storage="_bill_hotels", ThisKey="hotel_id", OtherKey="hotel_id")]
		public EntitySet<bill_hotel> bill_hotels
		{
			get
			{
				return this._bill_hotels;
			}
			set
			{
				this._bill_hotels.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bill_hotels(bill_hotel entity)
		{
			this.SendPropertyChanging();
			entity.hotel = this;
		}
		
		private void detach_bill_hotels(bill_hotel entity)
		{
			this.SendPropertyChanging();
			entity.hotel = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tour")]
	public partial class tour : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _tour_id;
		
		private string _tour_name;
		
		private System.Nullable<decimal> _price;
		
		private System.Nullable<System.DateTime> _departure_time;
		
		private System.Nullable<System.DateTime> _return_time;
		
		private System.Nullable<int> _status;
		
		private System.Nullable<long> _destination_id;
		
		private System.Nullable<long> _departure_id;
		
		private System.Nullable<long> _discount_id;
		
		private System.Nullable<long> _tour_type_id;
		
		private System.Nullable<System.DateTime> _create_date;
		
		private System.Nullable<System.DateTime> _update_create;
		
		private EntitySet<bill_tour> _bill_tours;
		
		private EntityRef<destination_point> _destination_point;
		
		private EntityRef<departure_point> _departure_point;
		
		private EntityRef<discount> _discount;
		
		private EntityRef<tour_type> _tour_type;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontour_idChanging(long value);
    partial void Ontour_idChanged();
    partial void Ontour_nameChanging(string value);
    partial void Ontour_nameChanged();
    partial void OnpriceChanging(System.Nullable<decimal> value);
    partial void OnpriceChanged();
    partial void Ondeparture_timeChanging(System.Nullable<System.DateTime> value);
    partial void Ondeparture_timeChanged();
    partial void Onreturn_timeChanging(System.Nullable<System.DateTime> value);
    partial void Onreturn_timeChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    partial void Ondestination_idChanging(System.Nullable<long> value);
    partial void Ondestination_idChanged();
    partial void Ondeparture_idChanging(System.Nullable<long> value);
    partial void Ondeparture_idChanged();
    partial void Ondiscount_idChanging(System.Nullable<long> value);
    partial void Ondiscount_idChanged();
    partial void Ontour_type_idChanging(System.Nullable<long> value);
    partial void Ontour_type_idChanged();
    partial void Oncreate_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreate_dateChanged();
    partial void Onupdate_createChanging(System.Nullable<System.DateTime> value);
    partial void Onupdate_createChanged();
    #endregion
		
		public tour()
		{
			this._bill_tours = new EntitySet<bill_tour>(new Action<bill_tour>(this.attach_bill_tours), new Action<bill_tour>(this.detach_bill_tours));
			this._destination_point = default(EntityRef<destination_point>);
			this._departure_point = default(EntityRef<departure_point>);
			this._discount = default(EntityRef<discount>);
			this._tour_type = default(EntityRef<tour_type>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tour_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long tour_id
		{
			get
			{
				return this._tour_id;
			}
			set
			{
				if ((this._tour_id != value))
				{
					this.Ontour_idChanging(value);
					this.SendPropertyChanging();
					this._tour_id = value;
					this.SendPropertyChanged("tour_id");
					this.Ontour_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tour_name", DbType="NVarChar(200)")]
		public string tour_name
		{
			get
			{
				return this._tour_name;
			}
			set
			{
				if ((this._tour_name != value))
				{
					this.Ontour_nameChanging(value);
					this.SendPropertyChanging();
					this._tour_name = value;
					this.SendPropertyChanged("tour_name");
					this.Ontour_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Decimal(18,2)")]
		public System.Nullable<decimal> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> departure_time
		{
			get
			{
				return this._departure_time;
			}
			set
			{
				if ((this._departure_time != value))
				{
					this.Ondeparture_timeChanging(value);
					this.SendPropertyChanging();
					this._departure_time = value;
					this.SendPropertyChanged("departure_time");
					this.Ondeparture_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_return_time", DbType="DateTime")]
		public System.Nullable<System.DateTime> return_time
		{
			get
			{
				return this._return_time;
			}
			set
			{
				if ((this._return_time != value))
				{
					this.Onreturn_timeChanging(value);
					this.SendPropertyChanging();
					this._return_time = value;
					this.SendPropertyChanged("return_time");
					this.Onreturn_timeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_destination_id", DbType="BigInt")]
		public System.Nullable<long> destination_id
		{
			get
			{
				return this._destination_id;
			}
			set
			{
				if ((this._destination_id != value))
				{
					if (this._destination_point.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondestination_idChanging(value);
					this.SendPropertyChanging();
					this._destination_id = value;
					this.SendPropertyChanged("destination_id");
					this.Ondestination_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_departure_id", DbType="BigInt")]
		public System.Nullable<long> departure_id
		{
			get
			{
				return this._departure_id;
			}
			set
			{
				if ((this._departure_id != value))
				{
					if (this._departure_point.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondeparture_idChanging(value);
					this.SendPropertyChanging();
					this._departure_id = value;
					this.SendPropertyChanged("departure_id");
					this.Ondeparture_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_discount_id", DbType="BigInt")]
		public System.Nullable<long> discount_id
		{
			get
			{
				return this._discount_id;
			}
			set
			{
				if ((this._discount_id != value))
				{
					if (this._discount.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ondiscount_idChanging(value);
					this.SendPropertyChanging();
					this._discount_id = value;
					this.SendPropertyChanged("discount_id");
					this.Ondiscount_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tour_type_id", DbType="BigInt")]
		public System.Nullable<long> tour_type_id
		{
			get
			{
				return this._tour_type_id;
			}
			set
			{
				if ((this._tour_type_id != value))
				{
					if (this._tour_type.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Ontour_type_idChanging(value);
					this.SendPropertyChanging();
					this._tour_type_id = value;
					this.SendPropertyChanged("tour_type_id");
					this.Ontour_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_create_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> create_date
		{
			get
			{
				return this._create_date;
			}
			set
			{
				if ((this._create_date != value))
				{
					this.Oncreate_dateChanging(value);
					this.SendPropertyChanging();
					this._create_date = value;
					this.SendPropertyChanged("create_date");
					this.Oncreate_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_update_create", DbType="DateTime")]
		public System.Nullable<System.DateTime> update_create
		{
			get
			{
				return this._update_create;
			}
			set
			{
				if ((this._update_create != value))
				{
					this.Onupdate_createChanging(value);
					this.SendPropertyChanging();
					this._update_create = value;
					this.SendPropertyChanged("update_create");
					this.Onupdate_createChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tour_bill_tour", Storage="_bill_tours", ThisKey="tour_id", OtherKey="tour_id")]
		public EntitySet<bill_tour> bill_tours
		{
			get
			{
				return this._bill_tours;
			}
			set
			{
				this._bill_tours.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="destination_point_tour", Storage="_destination_point", ThisKey="destination_id", OtherKey="destination_id", IsForeignKey=true)]
		public destination_point destination_point
		{
			get
			{
				return this._destination_point.Entity;
			}
			set
			{
				destination_point previousValue = this._destination_point.Entity;
				if (((previousValue != value) 
							|| (this._destination_point.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._destination_point.Entity = null;
						previousValue.tours.Remove(this);
					}
					this._destination_point.Entity = value;
					if ((value != null))
					{
						value.tours.Add(this);
						this._destination_id = value.destination_id;
					}
					else
					{
						this._destination_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("destination_point");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="departure_point_tour", Storage="_departure_point", ThisKey="departure_id", OtherKey="departure_id", IsForeignKey=true)]
		public departure_point departure_point
		{
			get
			{
				return this._departure_point.Entity;
			}
			set
			{
				departure_point previousValue = this._departure_point.Entity;
				if (((previousValue != value) 
							|| (this._departure_point.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._departure_point.Entity = null;
						previousValue.tours.Remove(this);
					}
					this._departure_point.Entity = value;
					if ((value != null))
					{
						value.tours.Add(this);
						this._departure_id = value.departure_id;
					}
					else
					{
						this._departure_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("departure_point");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="discount_tour", Storage="_discount", ThisKey="discount_id", OtherKey="discount_id", IsForeignKey=true)]
		public discount discount
		{
			get
			{
				return this._discount.Entity;
			}
			set
			{
				discount previousValue = this._discount.Entity;
				if (((previousValue != value) 
							|| (this._discount.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._discount.Entity = null;
						previousValue.tours.Remove(this);
					}
					this._discount.Entity = value;
					if ((value != null))
					{
						value.tours.Add(this);
						this._discount_id = value.discount_id;
					}
					else
					{
						this._discount_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("discount");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tour_type_tour", Storage="_tour_type", ThisKey="tour_type_id", OtherKey="tour_type_id", IsForeignKey=true)]
		public tour_type tour_type
		{
			get
			{
				return this._tour_type.Entity;
			}
			set
			{
				tour_type previousValue = this._tour_type.Entity;
				if (((previousValue != value) 
							|| (this._tour_type.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tour_type.Entity = null;
						previousValue.tours.Remove(this);
					}
					this._tour_type.Entity = value;
					if ((value != null))
					{
						value.tours.Add(this);
						this._tour_type_id = value.tour_type_id;
					}
					else
					{
						this._tour_type_id = default(Nullable<long>);
					}
					this.SendPropertyChanged("tour_type");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bill_tours(bill_tour entity)
		{
			this.SendPropertyChanging();
			entity.tour = this;
		}
		
		private void detach_bill_tours(bill_tour entity)
		{
			this.SendPropertyChanging();
			entity.tour = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tour_type")]
	public partial class tour_type : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _tour_type_id;
		
		private string _tour_type_name;
		
		private System.Nullable<int> _status;
		
		private EntitySet<tour> _tours;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ontour_type_idChanging(long value);
    partial void Ontour_type_idChanged();
    partial void Ontour_type_nameChanging(string value);
    partial void Ontour_type_nameChanged();
    partial void OnstatusChanging(System.Nullable<int> value);
    partial void OnstatusChanged();
    #endregion
		
		public tour_type()
		{
			this._tours = new EntitySet<tour>(new Action<tour>(this.attach_tours), new Action<tour>(this.detach_tours));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tour_type_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long tour_type_id
		{
			get
			{
				return this._tour_type_id;
			}
			set
			{
				if ((this._tour_type_id != value))
				{
					this.Ontour_type_idChanging(value);
					this.SendPropertyChanging();
					this._tour_type_id = value;
					this.SendPropertyChanged("tour_type_id");
					this.Ontour_type_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tour_type_name", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string tour_type_name
		{
			get
			{
				return this._tour_type_name;
			}
			set
			{
				if ((this._tour_type_name != value))
				{
					this.Ontour_type_nameChanging(value);
					this.SendPropertyChanging();
					this._tour_type_name = value;
					this.SendPropertyChanged("tour_type_name");
					this.Ontour_type_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="Int")]
		public System.Nullable<int> status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tour_type_tour", Storage="_tours", ThisKey="tour_type_id", OtherKey="tour_type_id")]
		public EntitySet<tour> tours
		{
			get
			{
				return this._tours;
			}
			set
			{
				this._tours.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.tour_type = this;
		}
		
		private void detach_tours(tour entity)
		{
			this.SendPropertyChanging();
			entity.tour_type = null;
		}
	}
}
#pragma warning restore 1591
